<a href="https://colab.research.google.com/github/Nakhwa123/PythonTraining/blob/master/PythonBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lists**

In [ ]:
List5 = [5,78,100]
for x in List5:
  print(x)

5
78
100


In [ ]:
List5 = [5,78,100]
if 100 in List5:
  print("Found")

Found


In [ ]:
List5 = [5,78,100]
print(len(List5))

3


In [ ]:
List5 = [5,78,100]
List5.append(10000)
print(List5)

[5, 78, 100, 10000]


In [ ]:
List5 = [5,78,100]
List5.insert(0,1999)
print(List5)

[1999, 5, 78, 100]


In [ ]:
List5 = [5,78,100]
List5.insert(1,1999)
print(List5)

[5, 1999, 78, 100]


In [ ]:
List5 = ["Nayan","Nakhwa"]
List5.insert(1,"Keshav")
print(List5)

['Nayan', 'Keshav', 'Nakhwa']


In [ ]:
List5 = ["Nayan","Nakhwa"]
List5.append("Best")
print(List5)

['Nayan', 'Nakhwa', 'Best']


In [ ]:
List5
List5.remove("Best")
print(List5)

['Nayan', 'Nakhwa']


In [ ]:
List5 = ["Nayan","Nakhwa","Best"]
List5.pop()
print(List5)

['Nayan', 'Nakhwa']


In [ ]:
List5 = ["Nayan","Nakhwa","Best"]
List5.pop(1)
print(List5)

['Nayan', 'Best']


In [ ]:
List5 = ["Nayan","Nakhwa","Best"]
del List5
print(List5)

NameError: ignored

In [ ]:
List5 = ["Nayan","Nakhwa","Best"]
del List5[0]
print(List5)

['Nakhwa', 'Best']


In [ ]:
#Clear
List5 = ["Nayan","Nakhwa","Best"]
List5.clear()
print(List5)

[]


In [ ]:
List5 = ["Nayan","Nakhwa","Best"]
copy1 = List5.copy()
print(copy1)

['Nayan', 'Nakhwa', 'Best']


In [ ]:
List5 = ["Nayan","Nakhwa","Best"]
List6 = list(List5)
print(List6)

['Nayan', 'Nakhwa', 'Best']


In [ ]:
5 and 6 and 7

In [ ]:
L = [1,2,3]
L1 = ['a','z','r']
L2 = L + L1
print(L2)

[1, 2, 3, 'a', 'z', 'r']


In [ ]:
L = [1,2,3]
L1 = ['a','z','r']
for x in L1:
  L.append(x)
print(L)

[1, 2, 3, 'a', 'z', 'r']


In [ ]:
L = [1,2,3]
L1 = ['a','z','r']
for x in L:
  L1.append(x)
print(L1)

['a', 'z', 'r', 1, 2, 3]


In [ ]:
L = [1,2,3]
L1 = ['a','z','r']
L.extend(L1)
print(L)

[1, 2, 3, 'a', 'z', 'r']


In [ ]:
L = ['c','a','f']
L.sort()
print(L)

['a', 'c', 'f']


In [ ]:
L8 = [4,7,2,3,5,6,7]
L8.sort()
print(L8)

[2, 3, 4, 5, 6, 7, 7]


In [ ]:
List6 = ["Nayan","Nakhwa","Best"]
List6.sort()
print(List6)

['Best', 'Nakhwa', 'Nayan']


In [ ]:
L8 = [4,7,2,3,5,6,7]
L8.sort(reverse = True)
print(L8)

[7, 7, 6, 5, 4, 3, 2]


In [ ]:
L8 = [4,7,2,3,5,6,7]
sum(L8)

34

In [ ]:
L8 = [4,7,2,3,5,6,7]
L9 = L8*10
print(L9)

[4, 7, 2, 3, 5, 6, 7, 4, 7, 2, 3, 5, 6, 7, 4, 7, 2, 3, 5, 6, 7, 4, 7, 2, 3, 5, 6, 7, 4, 7, 2, 3, 5, 6, 7, 4, 7, 2, 3, 5, 6, 7, 4, 7, 2, 3, 5, 6, 7, 4, 7, 2, 3, 5, 6, 7, 4, 7, 2, 3, 5, 6, 7, 4, 7, 2, 3, 5, 6, 7]


In [ ]:
L8 = [4,7,2,3,5,6,7]
min(L8)

2

In [ ]:
L8 = [4,7,2,3,5,6,2,2.000001]
type(L8)
min(L8)

2

In [ ]:
L8 = [4,7,2,3,5,6,7]
L8.reverse()
print(L8)

[7, 6, 5, 3, 2, 7, 4]


# **Tuples**

In [ ]:
Tup = (1,2,3,4,5)
print(Tup)

(1, 2, 3, 4, 5)


In [ ]:
Tup1 = ('Nayan', 'Nakhwa')
print(Tup1)

('Nayan', 'Nakhwa')


In [ ]:
Tup = (1,2,3,4,5)
print(Tup[-5])

1


In [ ]:
Tup3 = ('Apple', 'Samsung', 'Vivo', 'Oppo', 'Nokia')
print(Tup3[1])
print(Tup3[-4])

Samsung
Samsung


In [ ]:
Tup3 = ('Apple', 'Samsung', 'Vivo', 'Oppo', 'Nokia')
print(Tup3[1:4])

('Samsung', 'Vivo', 'Oppo')


In [ ]:
Tup3 = ('Apple', 'Samsung', 'Vivo', 'Oppo', 'Nokia')
print(Tup3[-5:-1])

('Apple', 'Samsung', 'Vivo', 'Oppo')


In [ ]:
Tup3 = ('Apple', 'Samsung', 'Vivo', 'Oppo', 'Nokia')
Tup3.append('A')
print(Tup3)

AttributeError: ignored

In [ ]:
Tup3 = ('Apple', 'Samsung', 'Vivo', 'Oppo', 'Nokia')
y = list(Tup3)
y[1] = "Huawei"
Tup3 = tuple(y)
print(Tup3)

('Apple', 'Huawei', 'Vivo', 'Oppo', 'Nokia')


In [ ]:
Tup3 = ('Apple', 'Samsung', 'Vivo', 'Oppo', 'Nokia')
if "Samsung" and "apple" in Tup3:
  print("Yes")
else:
  print("No")

No


In [ ]:
Tup3 = ('Apple', 'Samsung', 'Vivo', 'Oppo', 'Nokia')
print(len(Tup3))

5


In [ ]:
Tup3 = ('Apple', 'Samsung', 'Vivo', 'Oppo', 'Nokia')
del Tup3
print(Tup3)

NameError: ignored

In [ ]:
Tup3 = ('Apple', 'Samsung', 'Vivo', 'Oppo', 'Nokia')
Tup5 = (1,2,3,4)
Tup4 = Tup3 + Tup5
print(Tup4)

('Apple', 'Samsung', 'Vivo', 'Oppo', 'Nokia', 1, 2, 3, 4)


In [ ]:
Tup4.count("Samsung")

1

In [ ]:
min(Tup5)

1

In [ ]:
a = (100,98,65,43,32,21)
print(max(a))
print(min(a))
print(len(a))

100
21
6


# **Dictionaries**

In [ ]:
dict.keys(Dict1)

dict_keys(['Brand', 'Modal', 'Color', 'Memory'])

In [ ]:
dict.values(Dict1)

dict_values(['Iphone', '11Pro', 'Green', '256GB'])

In [ ]:
Dict1= {'Brand':'Iphone','Modal':'11Pro','Color':'Green','Memory':'256GB'}
print(Dict1)

{'Brand': 'Iphone', 'Modal': '11Pro', 'Color': 'Green', 'Memory': '256GB'}


In [ ]:
Y = Dict1.get("Brand")
print(Y)

Iphone


In [ ]:
Y = Dict1["Brand"]
print(Y)

Iphone


In [ ]:
for x in Dict1:
  print(Dict1[x])

Iphone
11Pro
Green
256GB


In [ ]:
for x in Dict1.values():
  print(x)

Iphone
11Pro
Green
256GB


In [ ]:
for x in Dict1.keys():
  print(x)

Brand
Modal
Color
Memory


In [ ]:
for x in Dict1:
  print(x)

Brand
Modal
Color
Memory


In [ ]:
for x,y in Dict1.items():
  print(x,y)

Brand Iphone
Modal 11Pro
Color Green
Memory 256GB


In [ ]:
if Brand in Dict1:
  print('Yes')

Yes


In [ ]:
Dict1= {'Brand':'Iphone','Modal':'11Pro','Color':'Green','Memory':'256GB'}
Dict1['Price'] = "Overpriced"
print(Dict1)

{'Brand': 'Iphone', 'Modal': '11Pro', 'Color': 'Green', 'Memory': '256GB', 'Price': 'Overpriced'}


In [ ]:
Dict1.pop("Price")
print(Dict1)

{'Brand': 'Iphone', 'Modal': '11Pro', 'Color': 'Green', 'Memory': '256GB'}


In [ ]:
Dict1.popitem()
print(Dict1)

{}


In [ ]:
Dict1= {'Brand':'Iphone','Modal':'11Pro','Color':'Green','Memory':'256GB'}
del Dict1["Modal"]
print(Dict1)

{'Brand': 'Iphone', 'Color': 'Green', 'Memory': '256GB'}


In [ ]:
Dict1= {'Brand':'Iphone','Modal':'11Pro','Color':'Green','Memory':'256GB'}
del Dict1
print(Dict1)

NameError: ignored

In [ ]:
Dict1= {'Brand':'Iphone','Modal':'11Pro','Color':'Green','Memory':'256GB'}
Dict1.clear()
print(Dict1)

{}


In [ ]:
Dict1= {'Brand':'Iphone','Modal':'11Pro','Color':'Green','Memory':'256GB'}
Y = Dict1.copy()
print(Y)

{'Brand': 'Iphone', 'Modal': '11Pro', 'Color': 'Green', 'Memory': '256GB'}


In [ ]:
Family = {"Child1": {"Name":"Nayan", "Age": "23"},"Child2": {"Name":"Shanaya", "Age": "20"}}
print(Family)

{'Child1': {'Name': 'Nayan', 'Age': '23'}, 'Child2': {'Name': 'Shanaya', 'Age': '20'}}


In [ ]:
Family = {"Child1": {"Name":"Nayan", "Age": "23"},"Child2": {"Name":"Shanaya", "Age": "20"},"Child3": {"Name":"Raghav", "Age": "100"}}

In [ ]:
Child1 = {"Name":"Nayan", "Age": "23"}
Child2 = {"Name":"Shanaya", "Age": "20"}
Child3 = {"Name":"Raghav", "Age": "100"}
Family = {"Child1":Child1, "Child2":Child2, "Child3":Child3}
print(Family)

{'Child1': {'Name': 'Nayan', 'Age': '23'}, 'Child2': {'Name': 'Shanaya', 'Age': '20'}, 'Child3': {'Name': 'Raghav', 'Age': '100'}}


# **Different Operators**

In [1]:
a = 8
print(a)

8


In [3]:
A = 8+7
A

15

In [5]:
A = 7**3
print(A)

343


In [6]:
X = 5
X = X + 3
print(X)

8


In [7]:
X = 5
X += 5
print(X)

10


In [9]:
if 5<3 or 7>4:
  print("Right")
else:
  print("Wrong")

Right


In [10]:
if 5<3 and 7>4:
  print("Right")
else:
  print("Wrong")

Wrong


In [14]:
A = "We Hate Covid"
print(A[3:])

Hate Covid


In [16]:
A = "We Hate Covid"
print(A[-10:])

Hate Covid


In [19]:
A = "We Hate Covid"
print(A.upper())

WE HATE COVID


In [20]:
A = "We Hate Covid"
print(A.lower())

we hate covid


In [21]:
A = "We Hate Covid"
print(A.replace("H",("L")))

We Late Covid


### **If Else Loop**

In [22]:
A = 15
B = 100
if A > B:
  print("aaaa")
else:
  print("dddd")

dddd


In [24]:
A = 50
B = 50
if A > B:
  print("aaaa")
elif A == B:
  print("dddd")
else:
  print("wwww")


dddd


In [25]:
X = 100
if X>20:
  print("Greater than 20")
elif X > 50:
  print("Greater than 50")
else:
  print("sssss")

Greater than 20


# **While Loop**

In [31]:
i = 2
while i < 100:
  print(i)
  i += 1

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [32]:
i = 2
while i < 100:
  print(i)
  if i == 50:
    break
  i += 1 

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


In [33]:
i = 2
while i < 100:
  print(i)
  i += 1
else:
  print("i is now equal to 100")

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
i is now equal to 100


# **For Loops**

In [34]:
A = [1,2,3,122,33,455,66,786]
for x in A:
  print(x)

1
2
3
122
33
455
66
786


In [35]:
for x in "Nayan":
  print(x)

N
a
y
a
n


In [37]:
Marvel = ["Ironman","Spiderman","Thor","Hulk"]
for x in Marvel:
  if x == "Hulk":
    break
  print(x)

Ironman
Spiderman
Thor


In [38]:
Marvel = ["Ironman","Spiderman","Thor","Hulk"]
for x in Marvel:
  if x == "Irnman":
    continue
  print(x)

Ironman
Spiderman
Thor
Hulk


In [39]:
for x in range(10):
  print(x)

0
1
2
3
4
5
6
7
8
9


In [41]:
for x in range(2,11):
  print(x)

2
3
4
5
6
7
8
9
10


In [43]:
for x in range(0,11,2):
  print(x)

0
2
4
6
8
10


In [46]:
Marvel = ["Ironman","Spiderman","Thor","Hulk"]
DC = ["Batman","Superman"]
for x in Marvel:
  for y in DC:
    print(x,y)

Ironman Batman
Ironman Superman
Spiderman Batman
Spiderman Superman
Thor Batman
Thor Superman
Hulk Batman
Hulk Superman


In [47]:
Marvel = ["Heads","Tails"]
DC = ["Heads","Tails"]
for x in Marvel:
  for y in DC:
    print(x,y)

Heads Heads
Heads Tails
Tails Heads
Tails Tails


In [49]:
age = 0
while (age<20):
  print("The age is:", age)
  age = age + 1
print("Good bye!")

The age is: 0
The age is: 1
The age is: 2
The age is: 3
The age is: 4
The age is: 5
The age is: 6
The age is: 7
The age is: 8
The age is: 9
The age is: 10
The age is: 11
The age is: 12
The age is: 13
The age is: 14
The age is: 15
The age is: 16
The age is: 17
The age is: 18
The age is: 19
Good bye!


# **Functions**

In [51]:
def my_function():
  print("This is my function")
my_function()

This is my function


## **Calculator**

In [55]:
def sum(a,b):
  return a+b
def Sub(a,b):
  return a-b
def mul(a,b):
  return a*b
def div(a,b):
  return a/b
d = 0
while d<10:
  a = int(input("enter a value: "))
  b = int(input("enter a value: "))
  print("Enter the operation please, 1 for add, 2 for sub, 4 for div")
  c = int(input("enter a value: "))
  if c == 1:
    print(sum(a,b))
  elif c == 2:
    print(Sub(a,b))
  elif c == 3:
    print(mul(a,b))
  elif c == 4:
    print(div(a,b))
  else:
    print("Error/Wrong Input")
  d = d+1


KeyboardInterrupt: ignored

In [ ]:
def sum(a,b):
  return a+b
def Sub(a,b):
  return a-b
def mul(a,b):
  return a*b
def div(a,b):
  return a/b
  a = int(input("enter a value: "))
  b = int(input("enter a value: "))
  print("Enter the operation please, 1 for add, 2 for sub, 4 for div")
  c = int(input("enter a value: "))
  if c == 1:
    print(sum(a,b))
  elif c == 2:
    print(Sub(a,b))
  elif c == 3:
    print(mul(a,b))
  elif c == 4:
    print(div(a,b))
  else:
    print("Error/Wrong Input")

## **Lambda Function**

In [56]:
#lambda function

x = lambda b : b + 20
print(x(5))

25


In [57]:
x = lambda b : b * 20
print(x(2))

40


In [58]:
x = lambda a,b : a * b
print(x(3,4))

12


In [59]:
y = lambda a,b,c : a*b+c
print(y(2,3,4))

10


In [61]:
print((lambda a,b,c : a*b+c)(2,3,4))

10


In [64]:
def nayan(x):
  return lambda a : a*x
Var1 = nayan(5)
print(Var1(10))

50


# **Numpy**

In [1]:
import numpy as np

In [3]:
list = [1,2,3,4]
arr = np.array(list)
type(arr)
print(arr)

[1 2 3 4]


In [8]:
list1 = [1,2,3,4]
list2 = [9,8,7,6]
list3 = [6,7,8,9]

arr1 = np.array([list1,list2,list3])
print(arr1)
type(arr1)

[[1 2 3 4]
 [9 8 7 6]
 [6 7 8 9]]


numpy.ndarray

In [9]:
arr1.shape

(3, 4)

In [10]:
arr1

array([[1, 2, 3, 4],
       [9, 8, 7, 6],
       [6, 7, 8, 9]])

In [13]:
arr1[2]

array([6, 7, 8, 9])

In [17]:
arr1[0:,:1]

array([[1],
       [9],
       [6]])

In [18]:
arr1[0:,:3]

array([[1, 2, 3],
       [9, 8, 7],
       [6, 7, 8]])

In [20]:
arr1[1:,:4]

array([[9, 8, 7, 6],
       [6, 7, 8, 9]])

In [22]:
arr1[:,:]

array([[1, 2, 3, 4],
       [9, 8, 7, 6],
       [6, 7, 8, 9]])

In [23]:
arr1[:,2:]

array([[3, 4],
       [7, 6],
       [8, 9]])

In [24]:
arr1[0:2,1:]

array([[2, 3, 4],
       [8, 7, 6]])

In [26]:
arr1[1:2,0:1]

array([[9]])

In [28]:
arr1[2:,3:]

array([[9]])

In [30]:
arr1[1:2,1:2]

array([[8]])

In [32]:
arr1[2:,2:3]

array([[8]])

In [33]:
list1 = [1,2,3,4]
list2 = [9,8,7,6]
list3 = [100,99,98,97]

arr = np.array([list1,list2,list3])
print(arr)

[[  1   2   3   4]
 [  9   8   7   6]
 [100  99  98  97]]


In [35]:
arr[2:,2:3]

array([[98]])

In [36]:
arr[2,2]

98

In [37]:
arr[1,2]

7

In [43]:
arr = np.array([[1,2,3,4,5],[9,8,7,6,5]])
arr.shape
print(arr)
arr

[[1 2 3 4 5]
 [9 8 7 6 5]]


array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 5]])

In [44]:
 print(arr[1,4])

5


In [53]:
arr1 = np.array([[1,2,3,4,5],[9,8,7,6]])
arr1

array([list([1, 2, 3, 4, 5]), list([9, 8, 7, 6])], dtype=object)

In [54]:
type(arr1)

numpy.ndarray

In [56]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr = np.arange(0,10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
arr = np.arange(0,12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
arr = np.arange(0,12).reshape(6,2)
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [67]:
np.random.rand(3,3)

array([[0.51274937, 0.59089576, 0.15446438],
       [0.13890691, 0.80055714, 0.75417122],
       [0.69491081, 0.60334648, 0.83399928]])

In [69]:
np.random.randn(3,3)

array([[ 1.38801022,  0.26773408, -1.27896589],
       [ 0.42400871,  1.0343887 , -0.56963175],
       [ 0.56826258,  0.97711692,  1.59253602]])

In [73]:
np.random.randint(1,13,4)

array([11,  5, 11,  2])

In [75]:
np.random.randint(1,12,100)

array([ 6,  9,  8, 10,  4,  8,  1, 10,  2,  2,  5,  1,  9,  1,  6,  4,  8,
        8, 10,  5,  9,  8,  6,  4,  8,  5, 10,  9,  5,  7,  4, 11,  9, 10,
       11, 10,  4,  6,  8,  5,  1,  7,  3,  9,  7,  9, 11,  9,  1,  1, 10,
        3,  5,  8,  1, 11,  7,  2,  6,  5,  6,  4, 11, 11,  9, 11,  8,  5,
        7, 10,  3,  7, 10,  8,  6,  5,  3, 11, 10, 11,  8,  7, 10,  1,  8,
        5,  3,  4,  2,  2,  3,  3,  9,  1,  5, 11,  9, 10,  3,  1])

In [78]:
np.random.randint(1,2,100).reshape(4,25)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1]])

In [80]:
np.random.random_sample((3,5))

array([[0.75360065, 0.26285826, 0.75891093, 0.29748867, 0.78384898],
       [0.22223734, 0.2529215 , 0.73692149, 0.38589579, 0.19156281],
       [0.8231189 , 0.43769064, 0.15685242, 0.28942401, 0.06197138]])

# **Pandas**

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame(np.arange(0,20).reshape(4,5),index = ['R1','R2','R3','R4'],columns = ['C1','C2','C3','C4','C5'])
df.head()

C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19

In [5]:
df.loc['R2']

C1    5
C2    6
C3    7
C4    8
C5    9
Name: R2, dtype: int64

In [6]:
df.loc[:,:]

C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19

In [11]:
df.iloc[:,1:]

C2  C3  C4  C5
R1   1   2   3   4
R2   6   7   8   9
R3  11  12  13  14
R4  16  17  18  19

In [12]:
df.iloc[:,1:].values

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [17]:
df['C1'].value_counts()

15    1
5     1
10    1
0     1
Name: C1, dtype: int64

## **Uploading DataSet**

In [18]:
from google.colab import files
uploaded = files.upload()

Saving Cars.csv to Cars.csv


In [19]:
data = pd.read_csv('Cars.csv')
data.head()

Price  Year  Mileage State   Make              Model
0  16472  2015    18681    MO  Buick  EncoreConvenience
1  15749  2015    27592    IN  Buick          EncoreFWD
2  16998  2015    13650    NC  Buick      EncoreLeather
3  15777  2015    25195    LA  Buick          EncoreFWD
4  16784  2015    22800    NV  Buick  EncoreConvenience

In [20]:
data.tail()

Price  Year  Mileage State       Make         Model
99995  15995  2010    94392    TX  Chevrolet     Camaro2dr
99996  36520  2016    20645    TX  Chevrolet  ColoradoCrew
99997  29999  2015    32055    TX  Chevrolet     Silverado
99998   9700  1997    97160    CA  Chevrolet   Corvette2dr
99999  34480  2014    29321    PA  Chevrolet     Silverado

In [21]:
data.describe()

Price           Year       Mileage
count  100000.000000  100000.000000  1.000000e+05
mean    21393.309250    2012.988740  5.800493e+04
std     13346.624403       3.599259  4.648996e+04
min      1500.000000    1997.000000  5.000000e+00
25%     12900.000000    2012.000000  2.650175e+04
50%     17995.000000    2014.000000  4.421850e+04
75%     27099.750000    2015.000000  8.000000e+04
max    429900.000000    2018.000000  2.457832e+06